name: RuboCop

on:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to get diff info
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run RuboCop on changed Ruby files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.rb')
          if [ -n "$CHANGED_FILES" ]; then
            echo "Running RuboCop on changed files:"
            echo "$CHANGED_FILES"
            bundle exec rubocop $CHANGED_FILES
          else
            echo "No Ruby files changed."
          fi
